default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ahmadraza
  password: 2050Mughal
  host: master.cgkh0pslnvyv.us-east-1.rds.amazonaws.com
  port: 5432

development:
  <<: *default
  database: sso_be_development

test:
  <<: *default
  database: sso_be_test

production:
  <<: *default
  database: sso_be_production
